import { uuidv4 } from '~/lib/utils';
import { dbSchema } from '~/utils/index.js';

// const tablesData = dbSchema['tables'];

const tablesData = [
  {
    schema: 'public',
    table: 'jobs',
    rows: 203,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'lead_id',
        ordinal_position: 8,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'jsi_submission_id',
        ordinal_position: 7,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'haf_submission_id',
        ordinal_position: 6,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'supervisor_id',
        ordinal_position: 5,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'estimation_id',
        ordinal_position: 4,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'warranty_claim_id',
        ordinal_position: 39,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_transferred',
        ordinal_position: 38,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'final_payment_id',
        ordinal_position: 37,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'deadline_start_date',
        ordinal_position: 36,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'estimation_labour_cost',
        ordinal_position: 35,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'0'::double precision",
        collation: null,
        comment: null,
      },
      {
        name: 'complete_date',
        ordinal_position: 34,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'deadline_year',
        ordinal_position: 33,
        type: 'integer',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'estimation_hours',
        ordinal_position: 30,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'0'::double precision",
        collation: null,
        comment: null,
      },
      {
        name: 'estimation_price',
        ordinal_position: 29,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'0'::double precision",
        collation: null,
        comment: null,
      },
      {
        name: 'business_id',
        ordinal_position: 19,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'division_id',
        ordinal_position: 18,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'season_id',
        ordinal_position: 17,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'booked_on',
        ordinal_position: 16,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'job_note',
        ordinal_position: 14,
        type: 'text',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'photos',
        ordinal_position: 28,
        type: 'array',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: "'{}'::character varying[]",
        collation: null,
        comment: null,
      },
      {
        name: 'agreement_no',
        ordinal_position: 27,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'related_job_id',
        ordinal_position: 21,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'job_id',
        ordinal_position: 20,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'production_deadline',
        ordinal_position: 12,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'difficulty',
        ordinal_position: 11,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'type',
        ordinal_position: 10,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'status',
        ordinal_position: 9,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [
      {
        foreign_key_name: 'FK_d85b7b57983a96244d14ad213c9',
        column: 'division_id',
        reference_schema: 'public',
        reference_table: 'divisions',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (division_id) REFERENCES divisions(id)',
      },
      {
        foreign_key_name: 'FK_1834d8d4e2714f15293fc9e0a9b',
        column: 'final_payment_id',
        reference_schema: 'public',
        reference_table: 'invoice_payments',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (final_payment_id) REFERENCES invoice_payments(id)',
      },
      {
        foreign_key_name: 'FK_5eb29aeb62c0784544437ced135',
        column: 'season_id',
        reference_schema: 'public',
        reference_table: 'seasons',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (season_id) REFERENCES seasons(id)',
      },
      {
        foreign_key_name: 'FK_6866bb3c271a60ec9156aa84569',
        column: 'business_id',
        reference_schema: 'public',
        reference_table: 'users',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (business_id) REFERENCES users(id)',
      },
      {
        foreign_key_name: 'FK_42e98c7ed00bcf786f2e4eb429a',
        column: 'warranty_claim_id',
        reference_schema: 'public',
        reference_table: 'warranty_claims',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (warranty_claim_id) REFERENCES warranty_claims(id)',
      },
      {
        foreign_key_name: 'FK_20c589975891d4dcb03c56d3a8c',
        column: 'lead_id',
        reference_schema: 'public',
        reference_table: 'leads',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (lead_id) REFERENCES leads(id)',
      },
      {
        foreign_key_name: 'FK_2b39cb95c6d38eddd095fef7a31',
        column: 'estimation_id',
        reference_schema: 'public',
        reference_table: 'estimations',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (estimation_id) REFERENCES estimations(id)',
      },
      {
        foreign_key_name: 'FK_761adefbce075a2db9a596937b5',
        column: 'supervisor_id',
        reference_schema: 'public',
        reference_table: 'users',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (supervisor_id) REFERENCES users(id)',
      },
      {
        foreign_key_name: 'FK_23e4ea4532b6d98ac16b9ccd7e9',
        column: 'haf_submission_id',
        reference_schema: 'public',
        reference_table: 'form_submissions',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (haf_submission_id) REFERENCES form_submissions(id)',
      },
      {
        foreign_key_name: 'FK_e2f5aa7422fc8b54ed1ec0ba230',
        column: 'jsi_submission_id',
        reference_schema: 'public',
        reference_table: 'form_submissions',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (jsi_submission_id) REFERENCES form_submissions(id)',
      },
    ],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'UQ_1834d8d4e2714f15293fc9e0a9b',
        column: 'final_payment_id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 193,
        column_position: 1,
        direction: 'ASC',
      },
      {
        index_name: 'PK_cf0a6c42b72fcc7f7c237def345',
        column: 'id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 193,
        column_position: 1,
        direction: 'ASC',
      },
      {
        index_name: 'UQ_75f2e130e4b1372fea0b6248a17',
        column: 'job_id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 193,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'divisions',
    rows: 2,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'division',
        ordinal_position: 4,
        type: 'character varying',
        character_maximum_length: 50,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'theme_color_name',
        ordinal_position: 5,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_c1f864477b3fd0954564108ed96',
        column: 'id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 0,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'invoice_payments',
    rows: 658,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'is_refund',
        ordinal_position: 19,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'un_claimed_e_transfer_id',
        ordinal_position: 18,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'past_payroll_id',
        ordinal_position: 16,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_archived',
        ordinal_position: 14,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'amount',
        ordinal_position: 13,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'0'::double precision",
        collation: null,
        comment: null,
      },
      {
        name: 'entered_date',
        ordinal_position: 11,
        type: 'date',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'payroll_id',
        ordinal_position: 10,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_deleted',
        ordinal_position: 9,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'invoice_id',
        ordinal_position: 6,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'ref_no',
        ordinal_position: 12,
        type: 'character varying',
        character_maximum_length: 70,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'reason',
        ordinal_position: 15,
        type: 'character varying',
        character_maximum_length: 150,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'attachment',
        ordinal_position: 17,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'name',
        ordinal_position: 4,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'status',
        ordinal_position: 8,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'payment_method',
        ordinal_position: 5,
        type: 'character varying',
        character_maximum_length: 50,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'nsf_payroll_id',
        ordinal_position: 21,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_valid',
        ordinal_position: 20,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'true',
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [
      {
        foreign_key_name: 'FK_9193ee41d24fd1f2d9bb919bfbb',
        column: 'un_claimed_e_transfer_id',
        reference_schema: 'public',
        reference_table: 'un_claimed_e_transfers',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (un_claimed_e_transfer_id) REFERENCES un_claimed_e_transfers(id)',
      },
      {
        foreign_key_name: 'FK_ceaf4f0d991598468e1d534232f',
        column: 'payroll_id',
        reference_schema: 'public',
        reference_table: 'payrolls',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (payroll_id) REFERENCES payrolls(id)',
      },
      {
        foreign_key_name: 'FK_e94fa427d3da279450dba6f4aa6',
        column: 'invoice_id',
        reference_schema: 'public',
        reference_table: 'invoices',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (invoice_id) REFERENCES invoices(id)',
      },
      {
        foreign_key_name: 'FK_af5b6404a73e90caeec9fc2b7cc',
        column: 'past_payroll_id',
        reference_schema: 'public',
        reference_table: 'payrolls',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (past_payroll_id) REFERENCES payrolls(id)',
      },
      {
        foreign_key_name: 'FK_5c479323320a4fef73773a284a7',
        column: 'nsf_payroll_id',
        reference_schema: 'public',
        reference_table: 'payrolls',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (nsf_payroll_id) REFERENCES payrolls(id)',
      },
    ],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_e19c9ebfa432289f510de7b4e99',
        column: 'id',
        index_type: 'btree',
        index_size: 49152,
        is_unique: true,
        cardinality: 639,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'seasons',
    rows: 11,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'end_date',
        ordinal_position: 6,
        type: 'date',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'start_date',
        ordinal_position: 5,
        type: 'date',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'is_deleted',
        ordinal_position: 7,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'name',
        ordinal_position: 4,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_cb8ed53b5fe109dcd4a4449ec9d',
        column: 'id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 0,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'users',
    rows: 224,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'phone_number',
        ordinal_position: 11,
        type: 'character varying',
        character_maximum_length: 20,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'language',
        ordinal_position: 12,
        type: 'character varying',
        character_maximum_length: 20,
        precision: null,
        nullable: false,
        default: "'en'::character varying",
        collation: null,
        comment: null,
      },
      {
        name: 'date_of_birth',
        ordinal_position: 16,
        type: 'character varying',
        character_maximum_length: 20,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'system_role',
        ordinal_position: 17,
        type: 'character varying',
        character_maximum_length: 20,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'join_on',
        ordinal_position: 18,
        type: 'character varying',
        character_maximum_length: 20,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'status',
        ordinal_position: 19,
        type: 'character varying',
        character_maximum_length: 100,
        precision: null,
        nullable: false,
        default: "'Invited'::character varying",
        collation: null,
        comment: null,
      },
      {
        name: 'full_name',
        ordinal_position: 20,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'last_name',
        ordinal_position: 5,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'application_id',
        ordinal_position: 21,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_login',
        ordinal_position: 14,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'true',
        collation: null,
        comment: null,
      },
      {
        name: 'first_name',
        ordinal_position: 4,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_super_admin',
        ordinal_position: 15,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'avatar',
        ordinal_position: 8,
        type: 'text',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'legal_last_name',
        ordinal_position: 7,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'email',
        ordinal_position: 9,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'legal_first_name',
        ordinal_position: 6,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'password',
        ordinal_position: 10,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_a3ffb1c0c8416b9fc6f907b7433',
        column: 'id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 222,
        column_position: 1,
        direction: 'ASC',
      },
      {
        index_name: 'UQ_97672ac88f789774dd47f7c8be3',
        column: 'email',
        index_type: 'btree',
        index_size: 40960,
        is_unique: true,
        cardinality: 222,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'warranty_claims',
    rows: 11,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'client_id',
        ordinal_position: 15,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'business_id',
        ordinal_position: 14,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'division_id',
        ordinal_position: 13,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'season_id',
        ordinal_position: 12,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'estimation_due_date',
        ordinal_position: 9,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'work_due_date',
        ordinal_position: 8,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'attachments',
        ordinal_position: 7,
        type: 'jsonb',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'client_contact_id',
        ordinal_position: 5,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'job_to_guarantee_id',
        ordinal_position: 4,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'description',
        ordinal_position: 6,
        type: 'text',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'option_id',
        ordinal_position: 16,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'status',
        ordinal_position: 10,
        type: 'character varying',
        character_maximum_length: 50,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [
      {
        foreign_key_name: 'FK_b81d7cdbd188bb533a60da069aa',
        column: 'season_id',
        reference_schema: 'public',
        reference_table: 'seasons',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (season_id) REFERENCES seasons(id)',
      },
      {
        foreign_key_name: 'FK_e80a31530b80de613ec3ab3b377',
        column: 'business_id',
        reference_schema: 'public',
        reference_table: 'users',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (business_id) REFERENCES users(id)',
      },
      {
        foreign_key_name: 'FK_a9ffb167812a105a2d7ffce32e3',
        column: 'option_id',
        reference_schema: 'public',
        reference_table: 'options',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (option_id) REFERENCES options(id)',
      },
      {
        foreign_key_name: 'FK_59880fd8b03926310e617dc0eda',
        column: 'job_to_guarantee_id',
        reference_schema: 'public',
        reference_table: 'jobs',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (job_to_guarantee_id) REFERENCES jobs(id)',
      },
      {
        foreign_key_name: 'FK_961bf86bd0a99a6d557aabe283a',
        column: 'division_id',
        reference_schema: 'public',
        reference_table: 'divisions',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (division_id) REFERENCES divisions(id)',
      },
      {
        foreign_key_name: 'FK_17dca3208b1b9395211e1f023b7',
        column: 'client_id',
        reference_schema: 'public',
        reference_table: 'clients',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (client_id) REFERENCES clients(id)',
      },
      {
        foreign_key_name: 'FK_4072876732067fd11124b2f13d0',
        column: 'client_contact_id',
        reference_schema: 'public',
        reference_table: 'client_contacts',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (client_contact_id) REFERENCES client_contacts(id)',
      },
    ],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_10984f957c4bc90ec2b9170214e',
        column: 'id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 0,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'leads',
    rows: 501,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'is_archived',
        ordinal_position: 8,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'lead_type',
        ordinal_position: 22,
        type: 'character varying',
        character_maximum_length: 30,
        precision: null,
        nullable: false,
        default: "'Original'::character varying",
        collation: null,
        comment: null,
      },
      {
        name: 'updated_by_id',
        ordinal_position: 5,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'warranty_claim_id',
        ordinal_position: 21,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'pined_location_id',
        ordinal_position: 20,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'marketing_session_id',
        ordinal_position: 19,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'client_contact_id',
        ordinal_position: 17,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'lead_id',
        ordinal_position: 18,
        type: 'character varying',
        character_maximum_length: 8,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'rating',
        ordinal_position: 11,
        type: 'character varying',
        character_maximum_length: 30,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'client_id',
        ordinal_position: 16,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'source',
        ordinal_position: 10,
        type: 'character varying',
        character_maximum_length: 30,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'division_id',
        ordinal_position: 14,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'season_id',
        ordinal_position: 13,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'business_id',
        ordinal_position: 12,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_converted',
        ordinal_position: 9,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'follow_up_date',
        ordinal_position: 7,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'created_by_id',
        ordinal_position: 4,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'job_description',
        ordinal_position: 6,
        type: 'text',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [
      {
        foreign_key_name: 'FK_0a4e4def4110a83bd59fca3ddb8',
        column: 'business_id',
        reference_schema: 'public',
        reference_table: 'users',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (business_id) REFERENCES users(id)',
      },
      {
        foreign_key_name: 'FK_91089388d1af7c0f930d93504be',
        column: 'client_contact_id',
        reference_schema: 'public',
        reference_table: 'client_contacts',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (client_contact_id) REFERENCES client_contacts(id)',
      },
      {
        foreign_key_name: 'FK_693c6a063d6bca119381b501da6',
        column: 'marketing_session_id',
        reference_schema: 'public',
        reference_table: 'marketing_sessions',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (marketing_session_id) REFERENCES marketing_sessions(id)',
      },
      {
        foreign_key_name: 'FK_15ec158ab4d5628c673419d4ade',
        column: 'client_id',
        reference_schema: 'public',
        reference_table: 'clients',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (client_id) REFERENCES clients(id)',
      },
      {
        foreign_key_name: 'FK_6488f0524aa9204fc04447afd90',
        column: 'season_id',
        reference_schema: 'public',
        reference_table: 'seasons',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (season_id) REFERENCES seasons(id)',
      },
      {
        foreign_key_name: 'FK_e65b191553551787d85e00b44f5',
        column: 'division_id',
        reference_schema: 'public',
        reference_table: 'divisions',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (division_id) REFERENCES divisions(id)',
      },
      {
        foreign_key_name: 'FK_5e85128fd9a7cb097d6ddc38d5f',
        column: 'pined_location_id',
        reference_schema: 'public',
        reference_table: 'pined_locations',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (pined_location_id) REFERENCES pined_locations(id)',
      },
      {
        foreign_key_name: 'FK_fc02decf8ddd6a218ff792565cb',
        column: 'warranty_claim_id',
        reference_schema: 'public',
        reference_table: 'warranty_claims',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (warranty_claim_id) REFERENCES warranty_claims(id)',
      },
    ],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_cd102ed7a9a4ca7d4d8bfeba406',
        column: 'id',
        index_type: 'btree',
        index_size: 40960,
        is_unique: true,
        cardinality: 493,
        column_position: 1,
        direction: 'ASC',
      },
      {
        index_name: 'UQ_d289409667aacd43214e3036807',
        column: 'lead_id',
        index_type: 'btree',
        index_size: 40960,
        is_unique: true,
        cardinality: 493,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
  {
    schema: 'public',
    table: 'estimations',
    rows: 267,
    type: 'BASE TABLE',
    comment: null,
    columns: [
      {
        name: 'follow_up_date',
        ordinal_position: 8,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'deadline_year',
        ordinal_position: 16,
        type: 'integer',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'final_price',
        ordinal_position: 17,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'full_price',
        ordinal_position: 18,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'0'::double precision",
        collation: null,
        comment: null,
      },
      {
        name: 'discount_price',
        ordinal_position: 19,
        type: 'double precision',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'0'::double precision",
        collation: null,
        comment: null,
      },
      {
        name: 'is_in_edit_estimation_flow',
        ordinal_position: 20,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'warranty_claim_id',
        ordinal_position: 21,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'status',
        ordinal_position: 6,
        type: 'character varying',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: "'Upcoming'::character varying",
        collation: null,
        comment: null,
      },
      {
        name: 'estimate_up_date',
        ordinal_position: 9,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'appt_date',
        ordinal_position: 10,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'is_generated_option',
        ordinal_position: 11,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'season_id',
        ordinal_position: 12,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'division_id',
        ordinal_position: 13,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'lead_id',
        ordinal_position: 4,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: null,
        collation: null,
        comment: null,
      },
      {
        name: 'updated_at',
        ordinal_position: 3,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'created_at',
        ordinal_position: 2,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'now()',
        collation: null,
        comment: null,
      },
      {
        name: 'id',
        ordinal_position: 1,
        type: 'uuid',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'uuid_generate_v4()',
        collation: null,
        comment: null,
      },
      {
        name: 'is_generated_agreement',
        ordinal_position: 14,
        type: 'boolean',
        character_maximum_length: null,
        precision: null,
        nullable: false,
        default: 'false',
        collation: null,
        comment: null,
      },
      {
        name: 'est_date',
        ordinal_position: 15,
        type: 'timestamp without time zone',
        character_maximum_length: null,
        precision: null,
        nullable: true,
        default: null,
        collation: null,
        comment: null,
      },
    ],
    foreign_keys: [
      {
        foreign_key_name: 'FK_159d55b596e18040b1956f40383',
        column: 'season_id',
        reference_schema: 'public',
        reference_table: 'seasons',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (season_id) REFERENCES seasons(id)',
      },
      {
        foreign_key_name: 'FK_c50bf889eac7233472abe555760',
        column: 'division_id',
        reference_schema: 'public',
        reference_table: 'divisions',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (division_id) REFERENCES divisions(id)',
      },
      {
        foreign_key_name: 'FK_c8c50d3b4749a4f18242395f781',
        column: 'lead_id',
        reference_schema: 'public',
        reference_table: 'leads',
        reference_column: 'id',
        fk_def: 'FOREIGN KEY (lead_id) REFERENCES leads(id)',
      },
      {
        foreign_key_name: 'FK_d0f6dfac0f89646629e4973ec7c',
        column: 'warranty_claim_id',
        reference_schema: 'public',
        reference_table: 'warranty_claims',
        reference_column: 'id',
        fk_def:
          'FOREIGN KEY (warranty_claim_id) REFERENCES warranty_claims(id)',
      },
    ],
    primary_keys: [{ column: 'id', pk_def: 'PRIMARY KEY (id)' }],
    indexes: [
      {
        index_name: 'PK_c7ec983ab9a4dccf21b74198cd6',
        column: 'id',
        index_type: 'btree',
        index_size: 16384,
        is_unique: true,
        cardinality: 255,
        column_position: 1,
        direction: 'ASC',
      },
    ],
  },
];

// generate position of table nodes
function genPos(n: number) {
  const res = [{ x: -192, y: -400 }]; // rect (384×800) ở tâm
  const dx = 384 + 100; // bước ngang  = 484 px
  const dy = 800 + 100; // bước dọc    = 900 px

  for (let r = 1; res.length < n; r++) {
    for (let i = -r; i <= r && res.length < n; i++)
      res.push({ x: i * dx - 192, y: -r * dy - 400 }); // top
    for (let j = -r + 1; j <= r && res.length < n; j++)
      res.push({ x: r * dx - 192, y: j * dy - 400 }); // right
    for (let i = r - 1; i >= -r && res.length < n; i--)
      res.push({ x: i * dx - 192, y: r * dy - 400 }); // bottom
    for (let j = r - 1; j >= -r + 1 && res.length < n; j--)
      res.push({ x: -r * dx - 192, y: j * dy - 400 }); // left
  }
  return res;
}

let tablesMaster: Record<string, number> = {};
tablesData.forEach((table, index) => {
  table.foreign_keys.forEach(foreignKey => {
    const referenceTable = foreignKey.reference_table;

    if (tablesMaster?.[`${referenceTable}`] === undefined) {
      tablesMaster[`${referenceTable}`] = 1;
    } else {
      tablesMaster[`${referenceTable}`] += 1;
    }
  });

  if (tablesMaster?.[`${table.table}`] === undefined) {
    tablesMaster[`${table.table}`] = 1;
  } else {
    tablesMaster[`${table.table}`] += 1;
  }
});

console.log(
  'tablesMaster',
  tablesMaster,

  Object.keys(tablesMaster).length,
  tablesMaster.length
);

/* Mảng toạ độ theo quy tắc “vòng đồng tâm – clockwise” */
const pos = genPos(Object.keys(tablesMaster).length); // đã viết ở bước trước

/* Sắp xếp giảm dần theo lượt tham chiếu + thêm toạ độ */
const sortedTablesMaster = Object.entries(tablesMaster)
  .sort((a, b) => b[1] - a[1]) // nhiều → ít
  .reduce(
    (acc, [table, count], i) => {
      acc[table] = { count, pos: pos[i] }; // chèn property pos
      return acc;
    },
    {} as Record<string, { count: number; pos: { x: number; y: number } }>
  );

console.log(
  'sortedTablesMaster',
  sortedTablesMaster,
  length,
  sortedTablesMaster.length
);
const tableName = 'achievement_badges';
const badgePos = sortedTablesMaster[tableName]?.pos;
console.log('badgePos', badgePos);

export const initialNodes = tablesData.map((table, index) => {
  const tableName = table.table;
  return {
    id: tableName,
    type: 'value',
    position: {
      x: sortedTablesMaster[tableName]?.pos.x,
      y: sortedTablesMaster[tableName]?.pos.y,
    },
    data: { value: table },
  };
});

// export const initialEdges = [];

export const initialEdges = (() => {
  const allEdges: {
    id: string;
    type: string;
    source: string;
    target: string;
    sourceHandle: string;
  }[][] = [];

  tablesData.forEach(table => {
    const tableEdges: {
      id: string;
      type: string;
      source: string;
      target: string;
      sourceHandle: string;
    }[] = [];

    table.foreign_keys.forEach(foreignKey => {
      tableEdges.push({
        id: uuidv4(),
        type: 'smoothstep',
        source: table.table,
        target: foreignKey.reference_table,
        sourceHandle: foreignKey.column,
      });
    });

    allEdges.push(tableEdges);
  });

  return allEdges;
})();
