const standardSqlKeyWord = [
  {
    keyword: 'ABSOLUTE',
    desc: 'SQL keyword "ABSOLUTE" used in cursor positioning.',
    example: 'FETCH ABSOLUTE 5 FROM cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'ACTION',
    desc: 'SQL keyword "ACTION" defines referential action for foreign keys.',
    example: 'ON DELETE ACTION;',
    type: 'keyword',
  },
  {
    keyword: 'ADD',
    desc: 'SQL keyword "ADD" adds a column or constraint.',
    example: 'ALTER TABLE users ADD age INT;',
    type: 'keyword',
  },
  {
    keyword: 'AFTER',
    desc: 'SQL keyword "AFTER" defines trigger timing.',
    example: 'CREATE TRIGGER trg AFTER INSERT ON users;',
    type: 'keyword',
  },
  {
    keyword: 'ALL',
    desc: 'SQL keyword "ALL" returns all matching rows including duplicates.',
    example: 'SELECT ALL name FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'ALLOCATE',
    desc: 'SQL keyword "ALLOCATE" assigns a prepared statement.',
    example: 'ALLOCATE cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'ALTER',
    desc: 'SQL keyword "ALTER" modifies existing database objects.',
    example: 'ALTER TABLE users ADD COLUMN email TEXT;',
    type: 'keyword',
  },
  {
    keyword: 'AND',
    desc: 'Logical operator "AND" combines conditions.',
    example: 'SELECT * FROM users WHERE age > 18 AND active = true;',
    type: 'keyword',
  },
  {
    keyword: 'ANY',
    desc: 'SQL keyword "ANY" compares a value to any value in a subquery.',
    example: 'SELECT * FROM users WHERE age > ANY (SELECT age FROM admins);',
    type: 'keyword',
  },
  {
    keyword: 'ARE',
    desc: 'SQL keyword "ARE" used in procedural or standard SQL constructs.',
    example: '-- Used in SQL procedural blocks;',
    type: 'keyword',
  },
  {
    keyword: 'AS',
    desc: 'SQL keyword "AS" assigns an alias.',
    example: 'SELECT name AS username FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'ASC',
    desc: 'SQL keyword "ASC" sorts results ascending.',
    example: 'SELECT * FROM users ORDER BY name ASC;',
    type: 'keyword',
  },
  {
    keyword: 'ASSERTION',
    desc: 'SQL keyword "ASSERTION" defines global constraints.',
    example: 'CREATE ASSERTION positive_balance CHECK (balance >= 0);',
    type: 'constraint',
  },
  {
    keyword: 'AT',
    desc: 'SQL keyword "AT" specifies location or time zone.',
    example: 'SET TIME ZONE AT LOCAL;',
    type: 'keyword',
  },
  {
    keyword: 'AUTHORIZATION',
    desc: 'SQL keyword "AUTHORIZATION" defines object owner.',
    example: 'CREATE SCHEMA my_schema AUTHORIZATION user1;',
    type: 'keyword',
  },
  {
    keyword: 'BEFORE',
    desc: 'SQL keyword "BEFORE" defines trigger timing.',
    example: 'CREATE TRIGGER trg BEFORE UPDATE ON users;',
    type: 'keyword',
  },
  {
    keyword: 'BEGIN',
    desc: 'SQL transaction keyword "BEGIN" starts a transaction block.',
    example: 'BEGIN;',
    type: 'transaction',
  },
  {
    keyword: 'BETWEEN',
    desc: 'SQL keyword "BETWEEN" filters a range of values.',
    example: 'SELECT * FROM users WHERE age BETWEEN 18 AND 30;',
    type: 'keyword',
  },
  {
    keyword: 'BOTH',
    desc: 'SQL keyword "BOTH" trims characters from both ends.',
    example: "TRIM(BOTH ' ' FROM name);",
    type: 'keyword',
  },
  {
    keyword: 'BREADTH',
    desc: 'SQL keyword "BREADTH" specifies breadth-first search in recursive queries.',
    example: 'SEARCH BREADTH FIRST BY column SET order_col;',
    type: 'keyword',
  },

  {
    keyword: 'BY',
    desc: 'SQL keyword "BY" defines grouping or ordering criteria.',
    example: 'SELECT * FROM users ORDER BY name;',
    type: 'keyword',
  },
  {
    keyword: 'CALL',
    desc: 'SQL keyword "CALL" executes a stored procedure.',
    example: 'CALL procedure_name();',
    type: 'keyword',
  },
  {
    keyword: 'CASCADE',
    desc: 'SQL keyword "CASCADE" propagates changes to dependent objects.',
    example: 'DROP TABLE users CASCADE;',
    type: 'keyword',
  },
  {
    keyword: 'CASCADED',
    desc: 'SQL keyword "CASCADED" specifies cascaded check option.',
    example:
      'CREATE VIEW v_users AS SELECT * FROM users WITH CASCADED CHECK OPTION;',
    type: 'keyword',
  },
  {
    keyword: 'CASE',
    desc: 'SQL keyword "CASE" defines conditional expressions.',
    example:
      "SELECT CASE WHEN age > 18 THEN 'Adult' ELSE 'Minor' END FROM users;",
    type: 'keyword',
  },
  {
    keyword: 'CAST',
    desc: 'SQL keyword "CAST" converts a value to a different data type.',
    example: 'SELECT CAST(age AS TEXT) FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'CATALOG',
    desc: 'SQL keyword "CATALOG" refers to database catalog metadata.',
    example: 'SELECT * FROM information_schema.catalogs;',
    type: 'keyword',
  },
  {
    keyword: 'CHECK',
    desc: 'SQL constraint "CHECK" ensures values satisfy a condition.',
    example: 'CREATE TABLE users (age INT CHECK (age >= 18));',
    type: 'constraint',
  },
  {
    keyword: 'CLOSE',
    desc: 'SQL keyword "CLOSE" closes a cursor.',
    example: 'CLOSE cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'COLLATE',
    desc: 'SQL keyword "COLLATE" sets collation for string comparison.',
    example: 'SELECT name COLLATE "en_US" FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'COLLATION',
    desc: 'SQL keyword "COLLATION" defines string sorting rules.',
    example: 'CREATE COLLATION my_collation;',
    type: 'keyword',
  },
  {
    keyword: 'COLUMN',
    desc: 'SQL keyword "COLUMN" refers to a table column.',
    example: 'ALTER TABLE users ADD COLUMN email TEXT;',
    type: 'keyword',
  },
  {
    keyword: 'COMMIT',
    desc: 'SQL transaction keyword "COMMIT" saves the current transaction.',
    example: 'COMMIT;',
    type: 'transaction',
  },
  {
    keyword: 'CONDITION',
    desc: 'SQL keyword "CONDITION" defines a condition in procedural SQL.',
    example: "DECLARE my_condition CONDITION FOR SQLSTATE '45000';",
    type: 'keyword',
  },
  {
    keyword: 'CONNECT',
    desc: 'SQL keyword "CONNECT" establishes a database connection (standard SQL).',
    example: 'CONNECT TO database_name;',
    type: 'keyword',
  },
  {
    keyword: 'CONNECTION',
    desc: 'SQL keyword "CONNECTION" refers to a database connection.',
    example: 'SET CONNECTION connection_name;',
    type: 'keyword',
  },
  {
    keyword: 'CONSTRAINT',
    desc: 'SQL keyword "CONSTRAINT" defines table constraints.',
    example: 'ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id);',
    type: 'constraint',
  },
  {
    keyword: 'CONSTRAINTS',
    desc: 'SQL keyword "CONSTRAINTS" refers to defined constraints.',
    example: 'SET CONSTRAINTS ALL IMMEDIATE;',
    type: 'constraint',
  },
  {
    keyword: 'CONSTRUCTOR',
    desc: 'SQL keyword "CONSTRUCTOR" defines structured type constructor.',
    example: '-- Used in object-relational SQL contexts;',
    type: 'keyword',
  },
  {
    keyword: 'CONTINUE',
    desc: 'SQL keyword "CONTINUE" resumes execution in procedural SQL.',
    example: 'CONTINUE;',
    type: 'keyword',
  },
  {
    keyword: 'CORRESPONDING',
    desc: 'SQL keyword "CORRESPONDING" matches columns in set operations.',
    example: 'SELECT * FROM table1 UNION CORRESPONDING SELECT * FROM table2;',
    type: 'keyword',
  },
  {
    keyword: 'COUNT',
    desc: 'SQL function "COUNT" returns number of rows.',
    example: 'SELECT COUNT(*) FROM users;',
    type: 'function',
  },
  {
    keyword: 'CREATE',
    desc: 'SQL keyword "CREATE" creates database objects.',
    example: 'CREATE TABLE users (id INT);',
    type: 'keyword',
  },
  {
    keyword: 'CROSS',
    desc: 'SQL keyword "CROSS" performs cross join.',
    example: 'SELECT * FROM users CROSS JOIN roles;',
    type: 'keyword',
  },
  {
    keyword: 'CUBE',
    desc: 'SQL keyword "CUBE" generates multidimensional aggregates.',
    example:
      'SELECT department, COUNT(*) FROM employees GROUP BY CUBE (department);',
    type: 'keyword',
  },
  {
    keyword: 'CURRENT',
    desc: 'SQL keyword "CURRENT" references current context value.',
    example: 'SELECT CURRENT_DATE;',
    type: 'keyword',
  },
  {
    keyword: 'CURRENT_DATE',
    desc: 'SQL keyword "CURRENT_DATE" returns current date.',
    example: 'SELECT CURRENT_DATE;',
    type: 'function',
  },
  {
    keyword: 'CURRENT_DEFAULT_TRANSFORM_GROUP',
    desc: 'SQL keyword for default transform group.',
    example: '-- Used in advanced SQL standard features;',
    type: 'keyword',
  },
  {
    keyword: 'CURRENT_TRANSFORM_GROUP_FOR_TYPE',
    desc: 'SQL keyword for transform group for a type.',
    example: '-- Used in advanced SQL standard features;',
    type: 'keyword',
  },
  {
    keyword: 'CURRENT_PATH',
    desc: 'SQL keyword "CURRENT_PATH" shows schema search path.',
    example: 'SHOW search_path;',
    type: 'keyword',
  },
  {
    keyword: 'CURRENT_ROLE',
    desc: 'SQL keyword "CURRENT_ROLE" returns current role.',
    example: 'SELECT CURRENT_ROLE;',
    type: 'function',
  },
  {
    keyword: 'CURRENT_TIME',
    desc: 'SQL keyword "CURRENT_TIME" returns current time.',
    example: 'SELECT CURRENT_TIME;',
    type: 'function',
  },
  {
    keyword: 'CURRENT_TIMESTAMP',
    desc: 'SQL keyword "CURRENT_TIMESTAMP" returns current timestamp.',
    example: 'SELECT CURRENT_TIMESTAMP;',
    type: 'function',
  },
  {
    keyword: 'CURRENT_USER',
    desc: 'SQL keyword "CURRENT_USER" returns current user.',
    example: 'SELECT CURRENT_USER;',
    type: 'function',
  },

  {
    keyword: 'CURSOR',
    desc: 'SQL keyword "CURSOR" defines a database cursor.',
    example: 'DECLARE cursor_name CURSOR FOR SELECT * FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'CYCLE',
    desc: 'SQL keyword "CYCLE" detects cycles in recursive queries.',
    example: 'CYCLE id SET is_cycle USING path;',
    type: 'keyword',
  },
  {
    keyword: 'DATA',
    desc: 'SQL keyword "DATA" refers to stored information.',
    example: '-- Used in SQL standard constructs;',
    type: 'keyword',
  },
  {
    keyword: 'DAY',
    desc: 'SQL keyword "DAY" represents day interval.',
    example: "INTERVAL '1' DAY;",
    type: 'keyword',
  },
  {
    keyword: 'DEALLOCATE',
    desc: 'SQL keyword "DEALLOCATE" removes a prepared statement.',
    example: 'DEALLOCATE PREPARE stmt_name;',
    type: 'keyword',
  },
  {
    keyword: 'DECLARE',
    desc: 'SQL keyword "DECLARE" defines variables or cursors.',
    example: 'DECLARE cursor_name CURSOR FOR SELECT * FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'DEFAULT',
    desc: 'SQL keyword "DEFAULT" sets default column value.',
    example: 'CREATE TABLE users (active BOOLEAN DEFAULT true);',
    type: 'keyword',
  },
  {
    keyword: 'DEFERRABLE',
    desc: 'SQL keyword "DEFERRABLE" allows constraint checking to be delayed.',
    example: 'CONSTRAINT fk_user DEFERRABLE INITIALLY DEFERRED;',
    type: 'constraint',
  },
  {
    keyword: 'DEFERRED',
    desc: 'SQL keyword "DEFERRED" delays constraint enforcement.',
    example: 'SET CONSTRAINTS ALL DEFERRED;',
    type: 'constraint',
  },
  {
    keyword: 'DELETE',
    desc: 'SQL keyword "DELETE" removes rows from a table.',
    example: 'DELETE FROM users WHERE id = 1;',
    type: 'keyword',
  },
  {
    keyword: 'DEPTH',
    desc: 'SQL keyword "DEPTH" specifies depth-first search in recursive queries.',
    example: 'SEARCH DEPTH FIRST BY id SET order_col;',
    type: 'keyword',
  },
  {
    keyword: 'DEREF',
    desc: 'SQL keyword "DEREF" dereferences a structured type reference.',
    example: '-- Used in object-relational SQL;',
    type: 'keyword',
  },
  {
    keyword: 'DESC',
    desc: 'SQL keyword "DESC" sorts results descending.',
    example: 'SELECT * FROM users ORDER BY name DESC;',
    type: 'keyword',
  },
  {
    keyword: 'DESCRIBE',
    desc: 'SQL keyword "DESCRIBE" shows table structure (dialect-specific).',
    example: 'DESCRIBE users;',
    type: 'keyword',
  },
  {
    keyword: 'DESCRIPTOR',
    desc: 'SQL keyword "DESCRIPTOR" references SQL descriptor areas.',
    example: '-- Used in advanced SQL contexts;',
    type: 'keyword',
  },
  {
    keyword: 'DETERMINISTIC',
    desc: 'SQL keyword "DETERMINISTIC" marks function as deterministic.',
    example: 'CREATE FUNCTION f() RETURNS INT DETERMINISTIC;',
    type: 'keyword',
  },
  {
    keyword: 'DIAGNOSTICS',
    desc: 'SQL keyword "DIAGNOSTICS" retrieves execution diagnostics.',
    example: 'GET DIAGNOSTICS variable = ROW_COUNT;',
    type: 'keyword',
  },
  {
    keyword: 'DISCONNECT',
    desc: 'SQL keyword "DISCONNECT" closes a database connection.',
    example: 'DISCONNECT CURRENT;',
    type: 'keyword',
  },
  {
    keyword: 'DISTINCT',
    desc: 'SQL keyword "DISTINCT" removes duplicate rows.',
    example: 'SELECT DISTINCT name FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'DO',
    desc: 'SQL keyword "DO" executes anonymous code block (PostgreSQL).',
    example: "DO $$ BEGIN RAISE NOTICE 'Hello'; END $$;",
    type: 'keyword',
  },
  {
    keyword: 'DOMAIN',
    desc: 'SQL keyword "DOMAIN" defines a custom data type.',
    example: 'CREATE DOMAIN positive_int AS INT CHECK (VALUE > 0);',
    type: 'keyword',
  },
  {
    keyword: 'DROP',
    desc: 'SQL keyword "DROP" removes database objects.',
    example: 'DROP TABLE users;',
    type: 'keyword',
  },
  {
    keyword: 'DYNAMIC',
    desc: 'SQL keyword "DYNAMIC" specifies dynamic cursor behavior.',
    example: '-- Used in cursor definitions;',
    type: 'keyword',
  },
  {
    keyword: 'EACH',
    desc: 'SQL keyword "EACH" specifies row-level trigger.',
    example: 'FOR EACH ROW EXECUTE FUNCTION trg_fn();',
    type: 'keyword',
  },
  {
    keyword: 'ELSE',
    desc: 'SQL keyword "ELSE" defines alternative branch in conditional.',
    example: "CASE WHEN age > 18 THEN 'Adult' ELSE 'Minor' END;",
    type: 'keyword',
  },
  {
    keyword: 'ELSEIF',
    desc: 'SQL keyword "ELSEIF" defines additional conditional branch.',
    example: '-- Used in procedural SQL;',
    type: 'keyword',
  },
  {
    keyword: 'END',
    desc: 'SQL keyword "END" closes block or conditional.',
    example: 'END;',
    type: 'keyword',
  },
  {
    keyword: 'END-EXEC',
    desc: 'SQL keyword "END-EXEC" terminates embedded SQL block.',
    example: 'END-EXEC;',
    type: 'keyword',
  },
  {
    keyword: 'EQUALS',
    desc: 'SQL keyword "EQUALS" represents equality comparison (standard).',
    example: 'WHERE age EQUALS 18;',
    type: 'keyword',
  },
  {
    keyword: 'ESCAPE',
    desc: 'SQL keyword "ESCAPE" defines escape character in LIKE.',
    example: "WHERE name LIKE '%!_%' ESCAPE '!';",
    type: 'keyword',
  },
  {
    keyword: 'EXCEPT',
    desc: 'SQL clause "EXCEPT" returns rows from first query not in second.',
    example: 'SELECT id FROM users EXCEPT SELECT id FROM admins;',
    type: 'clause',
  },
  {
    keyword: 'EXCEPTION',
    desc: 'SQL keyword "EXCEPTION" handles errors in procedural SQL.',
    example: 'EXCEPTION WHEN OTHERS THEN RAISE;',
    type: 'keyword',
  },
  {
    keyword: 'EXEC',
    desc: 'SQL keyword "EXEC" executes procedure (dialect-specific).',
    example: 'EXEC procedure_name;',
    type: 'keyword',
  },
  {
    keyword: 'EXECUTE',
    desc: 'SQL keyword "EXECUTE" runs prepared statement.',
    example: 'EXECUTE stmt_name;',
    type: 'keyword',
  },
  {
    keyword: 'EXISTS',
    desc: 'SQL keyword "EXISTS" tests existence of subquery rows.',
    example:
      'SELECT * FROM users WHERE EXISTS (SELECT 1 FROM orders WHERE orders.user_id = users.id);',
    type: 'keyword',
  },
  {
    keyword: 'EXIT',
    desc: 'SQL keyword "EXIT" exits loop in procedural SQL.',
    example: 'EXIT WHEN done;',
    type: 'keyword',
  },
  {
    keyword: 'EXTERNAL',
    desc: 'SQL keyword "EXTERNAL" defines external routine.',
    example: "CREATE FUNCTION f() RETURNS INT EXTERNAL NAME 'lib.so';",
    type: 'keyword',
  },
  {
    keyword: 'FETCH',
    desc: 'SQL keyword "FETCH" retrieves rows from cursor.',
    example: 'FETCH NEXT FROM cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'FIRST',
    desc: 'SQL keyword "FIRST" fetches first rows.',
    example: 'FETCH FIRST 10 ROWS ONLY;',
    type: 'keyword',
  },
  {
    keyword: 'FOR',
    desc: 'SQL keyword "FOR" defines loop or constraint behavior.',
    example: 'FOR UPDATE;',
    type: 'keyword',
  },
  {
    keyword: 'FOREIGN',
    desc: 'SQL constraint keyword "FOREIGN" defines foreign key.',
    example: 'FOREIGN KEY (user_id) REFERENCES users(id);',
    type: 'constraint',
  },
  {
    keyword: 'FOUND',
    desc: 'SQL keyword "FOUND" indicates result in procedural SQL.',
    example: 'IF FOUND THEN ... END IF;',
    type: 'keyword',
  },
  {
    keyword: 'FROM',
    desc: 'SQL clause "FROM" specifies source table.',
    example: 'SELECT * FROM users;',
    type: 'clause',
  },
  {
    keyword: 'FREE',
    desc: 'SQL keyword "FREE" releases locator.',
    example: 'FREE locator_name;',
    type: 'keyword',
  },
  {
    keyword: 'FULL',
    desc: 'SQL keyword "FULL" defines full outer join.',
    example:
      'SELECT * FROM users FULL JOIN orders ON users.id = orders.user_id;',
    type: 'keyword',
  },
  {
    keyword: 'FUNCTION',
    desc: 'SQL keyword "FUNCTION" defines stored function.',
    example: 'CREATE FUNCTION f() RETURNS INT AS $$ SELECT 1; $$ LANGUAGE SQL;',
    type: 'keyword',
  },
  {
    keyword: 'GENERAL',
    desc: 'SQL keyword "GENERAL" used in transform groups.',
    example: '-- Used in advanced SQL features;',
    type: 'keyword',
  },
  {
    keyword: 'GET',
    desc: 'SQL keyword "GET" retrieves diagnostics info.',
    example: 'GET DIAGNOSTICS var = ROW_COUNT;',
    type: 'keyword',
  },
  {
    keyword: 'GLOBAL',
    desc: 'SQL keyword "GLOBAL" defines global temporary table.',
    example: 'CREATE GLOBAL TEMPORARY TABLE temp_users;',
    type: 'keyword',
  },
  {
    keyword: 'GO',
    desc: 'SQL keyword "GO" batch separator (SQL Server).',
    example: 'GO',
    type: 'keyword',
  },
  {
    keyword: 'GOTO',
    desc: 'SQL keyword "GOTO" jumps to label (procedural).',
    example: 'GOTO label_name;',
    type: 'keyword',
  },
  {
    keyword: 'GRANT',
    desc: 'SQL keyword "GRANT" assigns privileges.',
    example: 'GRANT SELECT ON users TO user1;',
    type: 'keyword',
  },
  {
    keyword: 'GROUP',
    desc: 'SQL clause "GROUP" groups rows.',
    example: 'SELECT role, COUNT(*) FROM users GROUP BY role;',
    type: 'clause',
  },

  {
    keyword: 'GROUPING',
    desc: 'SQL keyword "GROUPING" returns grouping information in GROUP BY.',
    example: 'SELECT GROUPING(department) FROM employees GROUP BY department;',
    type: 'keyword',
  },
  {
    keyword: 'HANDLE',
    desc: 'SQL keyword "HANDLE" used in procedural SQL error handling.',
    example: '-- Used in SQL procedural contexts;',
    type: 'keyword',
  },
  {
    keyword: 'HAVING',
    desc: 'SQL clause "HAVING" filters grouped results.',
    example:
      'SELECT role, COUNT(*) FROM users GROUP BY role HAVING COUNT(*) > 5;',
    type: 'clause',
  },
  {
    keyword: 'HOLD',
    desc: 'SQL keyword "HOLD" keeps cursor open after commit.',
    example: 'DECLARE cursor_name CURSOR WITH HOLD FOR SELECT * FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'HOUR',
    desc: 'SQL keyword "HOUR" represents hour interval.',
    example: "INTERVAL '1' HOUR;",
    type: 'keyword',
  },
  {
    keyword: 'IDENTITY',
    desc: 'SQL keyword "IDENTITY" defines auto-increment column.',
    example: 'CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY);',
    type: 'keyword',
  },
  {
    keyword: 'IF',
    desc: 'SQL keyword "IF" defines conditional logic.',
    example: 'IF condition THEN statement; END IF;',
    type: 'keyword',
  },
  {
    keyword: 'IMMEDIATE',
    desc: 'SQL keyword "IMMEDIATE" enforces immediate constraint checking.',
    example: 'SET CONSTRAINTS ALL IMMEDIATE;',
    type: 'constraint',
  },
  {
    keyword: 'IN',
    desc: 'SQL keyword "IN" checks membership in a list or subquery.',
    example: 'SELECT * FROM users WHERE id IN (1,2,3);',
    type: 'keyword',
  },
  {
    keyword: 'INDICATOR',
    desc: 'SQL keyword "INDICATOR" used with host variables in embedded SQL.',
    example: '-- Used in embedded SQL;',
    type: 'keyword',
  },
  {
    keyword: 'INITIALLY',
    desc: 'SQL keyword "INITIALLY" defines initial constraint state.',
    example: 'CONSTRAINT fk_user DEFERRABLE INITIALLY DEFERRED;',
    type: 'constraint',
  },
  {
    keyword: 'INNER',
    desc: 'SQL keyword "INNER" defines inner join.',
    example:
      'SELECT * FROM users INNER JOIN orders ON users.id = orders.user_id;',
    type: 'keyword',
  },
  {
    keyword: 'INOUT',
    desc: 'SQL keyword "INOUT" defines input/output parameter.',
    example: 'CREATE PROCEDURE p(INOUT param INT);',
    type: 'keyword',
  },
  {
    keyword: 'INPUT',
    desc: 'SQL keyword "INPUT" used in procedural contexts.',
    example: '-- Used in SQL procedural features;',
    type: 'keyword',
  },
  {
    keyword: 'INSERT',
    desc: 'SQL keyword "INSERT" adds new rows.',
    example: "INSERT INTO users (name) VALUES ('John');",
    type: 'keyword',
  },
  {
    keyword: 'INTERSECT',
    desc: 'SQL clause "INTERSECT" returns common rows between queries.',
    example: 'SELECT id FROM users INTERSECT SELECT id FROM admins;',
    type: 'clause',
  },
  {
    keyword: 'INTO',
    desc: 'SQL keyword "INTO" specifies target table or variable.',
    example: "INSERT INTO users (name) VALUES ('John');",
    type: 'keyword',
  },
  {
    keyword: 'IS',
    desc: 'SQL keyword "IS" tests for null or boolean conditions.',
    example: 'SELECT * FROM users WHERE deleted_at IS NULL;',
    type: 'keyword',
  },
  {
    keyword: 'ISOLATION',
    desc: 'SQL keyword "ISOLATION" sets transaction isolation level.',
    example: 'SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;',
    type: 'transaction',
  },
  {
    keyword: 'JOIN',
    desc: 'SQL clause "JOIN" combines rows from tables.',
    example: 'SELECT * FROM users JOIN orders ON users.id = orders.user_id;',
    type: 'clause',
  },
  {
    keyword: 'KEY',
    desc: 'SQL keyword "KEY" defines primary or foreign key.',
    example: 'PRIMARY KEY (id);',
    type: 'constraint',
  },
  {
    keyword: 'LANGUAGE',
    desc: 'SQL keyword "LANGUAGE" defines function language.',
    example: 'CREATE FUNCTION f() RETURNS INT LANGUAGE SQL;',
    type: 'keyword',
  },
  {
    keyword: 'LAST',
    desc: 'SQL keyword "LAST" fetches last row.',
    example: 'FETCH LAST FROM cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'LATERAL',
    desc: 'SQL keyword "LATERAL" allows subquery to reference outer query.',
    example:
      'SELECT * FROM users, LATERAL (SELECT * FROM orders WHERE orders.user_id = users.id) o;',
    type: 'keyword',
  },
  {
    keyword: 'LEADING',
    desc: 'SQL keyword "LEADING" trims characters from start.',
    example: "TRIM(LEADING '0' FROM code);",
    type: 'keyword',
  },
  {
    keyword: 'LEAVE',
    desc: 'SQL keyword "LEAVE" exits loop in procedural SQL.',
    example: 'LEAVE loop_label;',
    type: 'keyword',
  },
  {
    keyword: 'LEFT',
    desc: 'SQL keyword "LEFT" defines left outer join.',
    example:
      'SELECT * FROM users LEFT JOIN orders ON users.id = orders.user_id;',
    type: 'keyword',
  },
  {
    keyword: 'LEVEL',
    desc: 'SQL keyword "LEVEL" used in hierarchical queries.',
    example: '-- Used in recursive queries;',
    type: 'keyword',
  },
  {
    keyword: 'LIKE',
    desc: 'SQL keyword "LIKE" performs pattern matching.',
    example: "SELECT * FROM users WHERE name LIKE 'A%';",
    type: 'keyword',
  },
  {
    keyword: 'LIMIT',
    desc: 'SQL clause "LIMIT" restricts result count.',
    example: 'SELECT * FROM users LIMIT 10;',
    type: 'clause',
  },
  {
    keyword: 'LOCAL',
    desc: 'SQL keyword "LOCAL" defines local context.',
    example: 'SET LOCAL search_path TO public;',
    type: 'keyword',
  },
  {
    keyword: 'LOCALTIME',
    desc: 'SQL function "LOCALTIME" returns current local time.',
    example: 'SELECT LOCALTIME;',
    type: 'function',
  },
  {
    keyword: 'LOCALTIMESTAMP',
    desc: 'SQL function "LOCALTIMESTAMP" returns current local timestamp.',
    example: 'SELECT LOCALTIMESTAMP;',
    type: 'function',
  },
  {
    keyword: 'LOCATOR',
    desc: 'SQL keyword "LOCATOR" references large object locator.',
    example: '-- Used with large objects;',
    type: 'keyword',
  },
  {
    keyword: 'LOOP',
    desc: 'SQL keyword "LOOP" defines loop block.',
    example: 'LOOP ... END LOOP;',
    type: 'keyword',
  },
  {
    keyword: 'MAP',
    desc: 'SQL keyword "MAP" used in transform definitions.',
    example: '-- Used in advanced SQL features;',
    type: 'keyword',
  },
  {
    keyword: 'MATCH',
    desc: 'SQL keyword "MATCH" defines foreign key match type.',
    example: 'FOREIGN KEY (user_id) REFERENCES users(id) MATCH FULL;',
    type: 'constraint',
  },
  {
    keyword: 'METHOD',
    desc: 'SQL keyword "METHOD" defines object method.',
    example: '-- Used in object-relational SQL;',
    type: 'keyword',
  },
  {
    keyword: 'MINUTE',
    desc: 'SQL keyword "MINUTE" represents minute interval.',
    example: "INTERVAL '5' MINUTE;",
    type: 'keyword',
  },
  {
    keyword: 'MODIFIES',
    desc: 'SQL keyword "MODIFIES" indicates routine modifies SQL data.',
    example: 'CREATE FUNCTION f() RETURNS INT MODIFIES SQL DATA;',
    type: 'keyword',
  },
  {
    keyword: 'MODULE',
    desc: 'SQL keyword "MODULE" defines SQL module.',
    example: '-- Used in SQL standard;',
    type: 'keyword',
  },
  {
    keyword: 'MONTH',
    desc: 'SQL keyword "MONTH" represents month interval.',
    example: "INTERVAL '1' MONTH;",
    type: 'keyword',
  },
  {
    keyword: 'NAMES',
    desc: 'SQL keyword "NAMES" sets client encoding (MySQL).',
    example: "SET NAMES 'utf8';",
    type: 'keyword',
  },
  {
    keyword: 'NATURAL',
    desc: 'SQL keyword "NATURAL" defines natural join.',
    example: 'SELECT * FROM users NATURAL JOIN orders;',
    type: 'keyword',
  },
  {
    keyword: 'NESTING',
    desc: 'SQL keyword "NESTING" used in nested table definitions.',
    example: '-- Used in advanced SQL features;',
    type: 'keyword',
  },
  {
    keyword: 'NEW',
    desc: 'SQL keyword "NEW" references new row in trigger.',
    example: 'NEW.column_name;',
    type: 'keyword',
  },
  {
    keyword: 'NEXT',
    desc: 'SQL keyword "NEXT" fetches next row.',
    example: 'FETCH NEXT FROM cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'NO',
    desc: 'SQL keyword "NO" negates options.',
    example: 'NO ACTION;',
    type: 'keyword',
  },
  {
    keyword: 'NONE',
    desc: 'SQL keyword "NONE" specifies no action.',
    example: '-- Used in constraints;',
    type: 'keyword',
  },
  {
    keyword: 'NOT',
    desc: 'SQL keyword "NOT" negates condition.',
    example: 'SELECT * FROM users WHERE active IS NOT NULL;',
    type: 'keyword',
  },
  {
    keyword: 'OF',
    desc: 'SQL keyword "OF" references object ownership or column list.',
    example: 'CREATE TRIGGER trg UPDATE OF column_name ON users;',
    type: 'keyword',
  },
  {
    keyword: 'OLD',
    desc: 'SQL keyword "OLD" references old row in trigger.',
    example: 'OLD.column_name;',
    type: 'keyword',
  },
  {
    keyword: 'ON',
    desc: 'SQL keyword "ON" defines join or trigger condition.',
    example: 'SELECT * FROM users JOIN orders ON users.id = orders.user_id;',
    type: 'keyword',
  },
  {
    keyword: 'ONLY',
    desc: 'SQL keyword "ONLY" restricts inheritance queries.',
    example: 'SELECT * FROM ONLY users;',
    type: 'keyword',
  },
  {
    keyword: 'OPEN',
    desc: 'SQL keyword "OPEN" opens cursor.',
    example: 'OPEN cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'OPTION',
    desc: 'SQL keyword "OPTION" defines query option.',
    example: 'WITH CHECK OPTION;',
    type: 'keyword',
  },
  {
    keyword: 'OR',
    desc: 'SQL keyword "OR" combines alternative conditions.',
    example: 'SELECT * FROM users WHERE age < 18 OR age > 60;',
    type: 'keyword',
  },
  {
    keyword: 'ORDER',
    desc: 'SQL clause "ORDER" sorts query results.',
    example: 'SELECT * FROM users ORDER BY name;',
    type: 'clause',
  },
  {
    keyword: 'ORDINALITY',
    desc: 'SQL keyword "ORDINALITY" adds row numbering in UNNEST.',
    example: 'SELECT * FROM UNNEST(array_col) WITH ORDINALITY;',
    type: 'keyword',
  },
  {
    keyword: 'OUT',
    desc: 'SQL keyword "OUT" defines output parameter.',
    example: 'CREATE PROCEDURE p(OUT param INT);',
    type: 'keyword',
  },
  {
    keyword: 'OUTER',
    desc: 'SQL keyword "OUTER" defines outer join.',
    example:
      'SELECT * FROM users LEFT OUTER JOIN orders ON users.id = orders.user_id;',
    type: 'keyword',
  },
  {
    keyword: 'OUTPUT',
    desc: 'SQL keyword "OUTPUT" returns affected rows (SQL Server).',
    example: "UPDATE users SET name='A' OUTPUT inserted.*;",
    type: 'keyword',
  },
  {
    keyword: 'OVERLAPS',
    desc: 'SQL keyword "OVERLAPS" checks time period overlap.',
    example: 'WHERE (start1, end1) OVERLAPS (start2, end2);',
    type: 'keyword',
  },
  {
    keyword: 'PAD',
    desc: 'SQL keyword "PAD" used in collation.',
    example: '-- Used in collation definition;',
    type: 'keyword',
  },
  {
    keyword: 'PARAMETER',
    desc: 'SQL keyword "PARAMETER" defines routine parameter.',
    example: '-- Used in SQL routine definitions;',
    type: 'keyword',
  },
  {
    keyword: 'PARTIAL',
    desc: 'SQL keyword "PARTIAL" used in match type.',
    example: 'MATCH PARTIAL;',
    type: 'constraint',
  },
  {
    keyword: 'PATH',
    desc: 'SQL keyword "PATH" sets search path.',
    example: 'SET search_path TO public;',
    type: 'keyword',
  },
  {
    keyword: 'PREPARE',
    desc: 'SQL keyword "PREPARE" creates prepared statement.',
    example: 'PREPARE stmt AS SELECT * FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'PRESERVE',
    desc: 'SQL keyword "PRESERVE" keeps rows in temp table.',
    example: 'ON COMMIT PRESERVE ROWS;',
    type: 'keyword',
  },
  {
    keyword: 'PRIMARY',
    desc: 'SQL constraint "PRIMARY KEY" uniquely identifies rows.',
    example: 'CREATE TABLE users (id INT PRIMARY KEY);',
    type: 'constraint',
  },

  {
    keyword: 'PRIOR',
    desc: 'SQL keyword "PRIOR" references parent row in hierarchical queries.',
    example: '-- Used in hierarchical queries;',
    type: 'keyword',
  },
  {
    keyword: 'PRIVILEGES',
    desc: 'SQL keyword "PRIVILEGES" refers to access rights.',
    example: 'GRANT ALL PRIVILEGES ON users TO user1;',
    type: 'keyword',
  },
  {
    keyword: 'PROCEDURE',
    desc: 'SQL keyword "PROCEDURE" defines stored procedure.',
    example: 'CREATE PROCEDURE p() LANGUAGE SQL AS $$ SELECT 1; $$;',
    type: 'keyword',
  },
  {
    keyword: 'PUBLIC',
    desc: 'SQL keyword "PUBLIC" refers to all users role.',
    example: 'GRANT SELECT ON users TO PUBLIC;',
    type: 'keyword',
  },
  {
    keyword: 'READ',
    desc: 'SQL keyword "READ" defines transaction read mode.',
    example: 'SET TRANSACTION READ ONLY;',
    type: 'transaction',
  },
  {
    keyword: 'READS',
    desc: 'SQL keyword "READS" indicates routine reads SQL data.',
    example: 'CREATE FUNCTION f() RETURNS INT READS SQL DATA;',
    type: 'keyword',
  },
  {
    keyword: 'RECURSIVE',
    desc: 'SQL keyword "RECURSIVE" enables recursive CTE.',
    example: 'WITH RECURSIVE cte AS (SELECT 1) SELECT * FROM cte;',
    type: 'keyword',
  },
  {
    keyword: 'REDO',
    desc: 'SQL keyword "REDO" reapplies transaction (dialect-specific).',
    example: '-- Dialect specific;',
    type: 'keyword',
  },
  {
    keyword: 'REF',
    desc: 'SQL keyword "REF" defines reference type.',
    example: '-- Used in object-relational SQL;',
    type: 'keyword',
  },
  {
    keyword: 'REFERENCES',
    desc: 'SQL constraint "REFERENCES" defines foreign key relation.',
    example: 'FOREIGN KEY (user_id) REFERENCES users(id);',
    type: 'constraint',
  },
  {
    keyword: 'REFERENCING',
    desc: 'SQL keyword "REFERENCING" defines trigger transition tables.',
    example: 'REFERENCING NEW TABLE AS new_table;',
    type: 'keyword',
  },
  {
    keyword: 'RELATIVE',
    desc: 'SQL keyword "RELATIVE" fetches cursor relative position.',
    example: 'FETCH RELATIVE 1 FROM cursor_name;',
    type: 'keyword',
  },
  {
    keyword: 'RELEASE',
    desc: 'SQL keyword "RELEASE" removes savepoint.',
    example: 'RELEASE SAVEPOINT sp1;',
    type: 'transaction',
  },
  {
    keyword: 'REPEAT',
    desc: 'SQL keyword "REPEAT" defines loop block.',
    example: 'REPEAT ... UNTIL condition END REPEAT;',
    type: 'keyword',
  },
  {
    keyword: 'RESIGNAL',
    desc: 'SQL keyword "RESIGNAL" rethrows exception.',
    example: 'RESIGNAL;',
    type: 'keyword',
  },
  {
    keyword: 'RESTRICT',
    desc: 'SQL keyword "RESTRICT" prevents cascading action.',
    example: 'DROP TABLE users RESTRICT;',
    type: 'keyword',
  },
  {
    keyword: 'RESULT',
    desc: 'SQL keyword "RESULT" defines result set in procedures.',
    example: '-- Used in SQL procedures;',
    type: 'keyword',
  },
  {
    keyword: 'RETURN',
    desc: 'SQL keyword "RETURN" exits function with value.',
    example: 'RETURN 1;',
    type: 'keyword',
  },
  {
    keyword: 'RETURNS',
    desc: 'SQL keyword "RETURNS" defines function return type.',
    example: 'CREATE FUNCTION f() RETURNS INT;',
    type: 'keyword',
  },
  {
    keyword: 'REVOKE',
    desc: 'SQL keyword "REVOKE" removes privileges.',
    example: 'REVOKE SELECT ON users FROM user1;',
    type: 'keyword',
  },
  {
    keyword: 'RIGHT',
    desc: 'SQL keyword "RIGHT" defines right outer join.',
    example:
      'SELECT * FROM users RIGHT JOIN orders ON users.id = orders.user_id;',
    type: 'keyword',
  },
  {
    keyword: 'ROLE',
    desc: 'SQL keyword "ROLE" defines or references role.',
    example: 'CREATE ROLE admin;',
    type: 'keyword',
  },
  {
    keyword: 'ROLLBACK',
    desc: 'SQL transaction keyword "ROLLBACK" reverts transaction.',
    example: 'ROLLBACK;',
    type: 'transaction',
  },
  {
    keyword: 'ROLLUP',
    desc: 'SQL keyword "ROLLUP" generates hierarchical aggregates.',
    example:
      'SELECT department, COUNT(*) FROM employees GROUP BY ROLLUP(department);',
    type: 'keyword',
  },
  {
    keyword: 'ROUTINE',
    desc: 'SQL keyword "ROUTINE" refers to stored routine.',
    example: '-- Used in information_schema;',
    type: 'keyword',
  },
  {
    keyword: 'ROW',
    desc: 'SQL keyword "ROW" defines row constructor.',
    example: "SELECT ROW(1, 'A');",
    type: 'keyword',
  },
  {
    keyword: 'ROWS',
    desc: 'SQL keyword "ROWS" defines row count limitation.',
    example: 'FETCH FIRST 10 ROWS ONLY;',
    type: 'keyword',
  },
  {
    keyword: 'SAVEPOINT',
    desc: 'SQL transaction keyword "SAVEPOINT" creates transaction savepoint.',
    example: 'SAVEPOINT sp1;',
    type: 'transaction',
  },
  {
    keyword: 'SCHEMA',
    desc: 'SQL keyword "SCHEMA" defines database schema.',
    example: 'CREATE SCHEMA my_schema;',
    type: 'keyword',
  },
  {
    keyword: 'SCROLL',
    desc: 'SQL keyword "SCROLL" defines scrollable cursor.',
    example: 'DECLARE cursor_name SCROLL CURSOR FOR SELECT * FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'SEARCH',
    desc: 'SQL keyword "SEARCH" defines recursive query order.',
    example: 'SEARCH DEPTH FIRST BY id SET order_col;',
    type: 'keyword',
  },
  {
    keyword: 'SECOND',
    desc: 'SQL keyword "SECOND" represents second interval.',
    example: "INTERVAL '10' SECOND;",
    type: 'keyword',
  },
  {
    keyword: 'SECTION',
    desc: 'SQL keyword "SECTION" used in embedded SQL.',
    example: '-- Used in embedded SQL;',
    type: 'keyword',
  },
  {
    keyword: 'SELECT',
    desc: 'SQL clause "SELECT" retrieves data.',
    example: 'SELECT * FROM users;',
    type: 'clause',
  },
  {
    keyword: 'SESSION',
    desc: 'SQL keyword "SESSION" refers to current session.',
    example: 'SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY;',
    type: 'keyword',
  },
  {
    keyword: 'SESSION_USER',
    desc: 'SQL function "SESSION_USER" returns session user.',
    example: 'SELECT SESSION_USER;',
    type: 'function',
  },
  {
    keyword: 'SET',
    desc: 'SQL keyword "SET" assigns configuration value.',
    example: 'SET search_path TO public;',
    type: 'keyword',
  },
  {
    keyword: 'SETS',
    desc: 'SQL keyword "SETS" used in grouping sets.',
    example: 'GROUP BY GROUPING SETS ((department));',
    type: 'keyword',
  },
  {
    keyword: 'SIGNAL',
    desc: 'SQL keyword "SIGNAL" raises exception.',
    example: "SIGNAL SQLSTATE '45000';",
    type: 'keyword',
  },
  {
    keyword: 'SIMILAR',
    desc: 'SQL keyword "SIMILAR" performs regex pattern matching.',
    example: "SELECT * FROM users WHERE name SIMILAR TO '(A|B)%';",
    type: 'keyword',
  },
  {
    keyword: 'SIZE',
    desc: 'SQL keyword "SIZE" used in type definitions.',
    example: '-- Used in SQL standard;',
    type: 'keyword',
  },
  {
    keyword: 'SOME',
    desc: 'SQL keyword "SOME" synonym for ANY.',
    example: 'SELECT * FROM users WHERE age > SOME (SELECT age FROM admins);',
    type: 'keyword',
  },
  {
    keyword: 'SPACE',
    desc: 'SQL keyword "SPACE" used in collation.',
    example: '-- Used in collation definition;',
    type: 'keyword',
  },
  {
    keyword: 'SPECIFIC',
    desc: 'SQL keyword "SPECIFIC" names routine.',
    example: 'CREATE FUNCTION f() RETURNS INT SPECIFIC f_spec;',
    type: 'keyword',
  },
  {
    keyword: 'SPECIFICTYPE',
    desc: 'SQL keyword "SPECIFICTYPE" used in structured types.',
    example: '-- Advanced SQL feature;',
    type: 'keyword',
  },
  {
    keyword: 'SQL',
    desc: 'SQL keyword "SQL" refers to SQL language.',
    example: 'LANGUAGE SQL;',
    type: 'keyword',
  },
  {
    keyword: 'SQLEXCEPTION',
    desc: 'SQL keyword "SQLEXCEPTION" handles SQL error.',
    example: 'DECLARE EXIT HANDLER FOR SQLEXCEPTION;',
    type: 'keyword',
  },
  {
    keyword: 'SQLSTATE',
    desc: 'SQL keyword "SQLSTATE" returns error code.',
    example: "SIGNAL SQLSTATE '45000';",
    type: 'keyword',
  },
  {
    keyword: 'SQLWARNING',
    desc: 'SQL keyword "SQLWARNING" handles SQL warning.',
    example: 'DECLARE CONTINUE HANDLER FOR SQLWARNING;',
    type: 'keyword',
  },
  {
    keyword: 'START',
    desc: 'SQL keyword "START" begins transaction.',
    example: 'START TRANSACTION;',
    type: 'transaction',
  },
  {
    keyword: 'STATE',
    desc: 'SQL keyword "STATE" references SQL state.',
    example: '-- Used in SQLSTATE contexts;',
    type: 'keyword',
  },
  {
    keyword: 'STATIC',
    desc: 'SQL keyword "STATIC" defines static cursor.',
    example: '-- Used in cursor definitions;',
    type: 'keyword',
  },
  {
    keyword: 'SYSTEM_USER',
    desc: 'SQL function "SYSTEM_USER" returns system user.',
    example: 'SELECT SYSTEM_USER;',
    type: 'function',
  },
  {
    keyword: 'TABLE',
    desc: 'SQL keyword "TABLE" defines or references table.',
    example: 'CREATE TABLE users (id INT);',
    type: 'keyword',
  },
  {
    keyword: 'TEMPORARY',
    desc: 'SQL keyword "TEMPORARY" defines temp table.',
    example: 'CREATE TEMPORARY TABLE temp_users (id INT);',
    type: 'keyword',
  },
  {
    keyword: 'THEN',
    desc: 'SQL keyword "THEN" used in conditional.',
    example: "CASE WHEN age > 18 THEN 'Adult' END;",
    type: 'keyword',
  },
  {
    keyword: 'TIMEZONE_HOUR',
    desc: 'SQL keyword "TIMEZONE_HOUR" extracts timezone hour.',
    example: 'EXTRACT(TIMEZONE_HOUR FROM CURRENT_TIMESTAMP);',
    type: 'function',
  },
  {
    keyword: 'TIMEZONE_MINUTE',
    desc: 'SQL keyword "TIMEZONE_MINUTE" extracts timezone minute.',
    example: 'EXTRACT(TIMEZONE_MINUTE FROM CURRENT_TIMESTAMP);',
    type: 'function',
  },
  {
    keyword: 'TO',
    desc: 'SQL keyword "TO" specifies target.',
    example: 'GRANT SELECT ON users TO user1;',
    type: 'keyword',
  },
  {
    keyword: 'TRAILING',
    desc: 'SQL keyword "TRAILING" trims trailing characters.',
    example: "TRIM(TRAILING ' ' FROM name);",
    type: 'keyword',
  },
  {
    keyword: 'TRANSACTION',
    desc: 'SQL keyword "TRANSACTION" defines transaction block.',
    example: 'START TRANSACTION;',
    type: 'transaction',
  },
  {
    keyword: 'TRANSLATION',
    desc: 'SQL keyword "TRANSLATION" defines translation.',
    example: '-- Advanced SQL feature;',
    type: 'keyword',
  },
  {
    keyword: 'TREAT',
    desc: 'SQL keyword "TREAT" casts structured type.',
    example: 'SELECT TREAT(value AS subtype);',
    type: 'keyword',
  },
  {
    keyword: 'TRIGGER',
    desc: 'SQL keyword "TRIGGER" defines database trigger.',
    example: 'CREATE TRIGGER trg BEFORE INSERT ON users;',
    type: 'keyword',
  },
  {
    keyword: 'UNDER',
    desc: 'SQL keyword "UNDER" defines subtype hierarchy.',
    example: '-- Used in object-relational SQL;',
    type: 'keyword',
  },
  {
    keyword: 'UNDO',
    desc: 'SQL keyword "UNDO" reverts transaction (dialect-specific).',
    example: '-- Dialect specific;',
    type: 'keyword',
  },
  {
    keyword: 'UNION',
    desc: 'SQL clause "UNION" combines result sets.',
    example: 'SELECT id FROM users UNION SELECT id FROM admins;',
    type: 'clause',
  },
  {
    keyword: 'UNIQUE',
    desc: 'SQL constraint "UNIQUE" enforces unique values.',
    example: 'CREATE TABLE users (email TEXT UNIQUE);',
    type: 'constraint',
  },
  {
    keyword: 'UNNEST',
    desc: 'SQL keyword "UNNEST" expands array into rows.',
    example: 'SELECT * FROM UNNEST(array_col);',
    type: 'keyword',
  },
  {
    keyword: 'UNTIL',
    desc: 'SQL keyword "UNTIL" defines loop termination.',
    example: 'REPEAT ... UNTIL condition END REPEAT;',
    type: 'keyword',
  },
  {
    keyword: 'UPDATE',
    desc: 'SQL keyword "UPDATE" modifies rows.',
    example: "UPDATE users SET name='A' WHERE id=1;",
    type: 'keyword',
  },
  {
    keyword: 'USAGE',
    desc: 'SQL keyword "USAGE" grants usage privilege.',
    example: 'GRANT USAGE ON SCHEMA public TO user1;',
    type: 'keyword',
  },
  {
    keyword: 'USER',
    desc: 'SQL keyword "USER" returns current user.',
    example: 'SELECT USER;',
    type: 'function',
  },
  {
    keyword: 'USING',
    desc: 'SQL keyword "USING" defines join or index clause.',
    example: 'SELECT * FROM users JOIN orders USING (user_id);',
    type: 'keyword',
  },
  {
    keyword: 'VALUE',
    desc: 'SQL keyword "VALUE" references domain value.',
    example: 'CHECK (VALUE > 0);',
    type: 'keyword',
  },
  {
    keyword: 'VALUES',
    desc: 'SQL keyword "VALUES" inserts row values.',
    example: "INSERT INTO users VALUES (1, 'John');",
    type: 'keyword',
  },
  {
    keyword: 'VIEW',
    desc: 'SQL keyword "VIEW" defines database view.',
    example: 'CREATE VIEW v_users AS SELECT * FROM users;',
    type: 'keyword',
  },
  {
    keyword: 'WHEN',
    desc: 'SQL keyword "WHEN" defines condition branch.',
    example: "CASE WHEN age > 18 THEN 'Adult' END;",
    type: 'keyword',
  },
  {
    keyword: 'WHENEVER',
    desc: 'SQL keyword "WHENEVER" handles embedded SQL condition.',
    example: 'WHENEVER SQLERROR CONTINUE;',
    type: 'keyword',
  },
  {
    keyword: 'WHERE',
    desc: 'SQL clause "WHERE" filters rows.',
    example: 'SELECT * FROM users WHERE age > 18;',
    type: 'clause',
  },
  {
    keyword: 'WHILE',
    desc: 'SQL keyword "WHILE" defines loop.',
    example: 'WHILE condition LOOP ... END LOOP;',
    type: 'keyword',
  },
  {
    keyword: 'WITH',
    desc: 'SQL keyword "WITH" defines CTE.',
    example: 'WITH cte AS (SELECT 1) SELECT * FROM cte;',
    type: 'keyword',
  },
  {
    keyword: 'WITHOUT',
    desc: 'SQL keyword "WITHOUT" excludes option.',
    example: 'CREATE TABLE t (id INT) WITHOUT OIDS;',
    type: 'keyword',
  },
  {
    keyword: 'WORK',
    desc: 'SQL keyword "WORK" synonym for transaction.',
    example: 'COMMIT WORK;',
    type: 'transaction',
  },
  {
    keyword: 'WRITE',
    desc: 'SQL keyword "WRITE" defines transaction mode.',
    example: 'SET TRANSACTION READ WRITE;',
    type: 'transaction',
  },
  {
    keyword: 'YEAR',
    desc: 'SQL keyword "YEAR" represents year interval.',
    example: "INTERVAL '1' YEAR;",
    type: 'keyword',
  },
  {
    keyword: 'ZONE',
    desc: 'SQL keyword "ZONE" defines time zone.',
    example: "SET TIME ZONE 'UTC';",
    type: 'keyword',
  },
];
