version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: cinny09/orca-q
    container_name: app1
    expose:
      - "3000"

  app2:
    image: cinny09/orca-q
    container_name: app2
    expose:
      - "3000"

  app3:
    image: cinny09/orca-q
    container_name: app3
    expose:
      - "3000"
